import { NgModule } from '@angular/core';
import { EffectsModule } from '@ngrx/effects';
import * as fromRouter from '@ngrx/router-store';
import { StoreModule } from '@ngrx/store';

import { STORE } from '@console-core/config';

import {
  AccountEffects,
  AccountFacade,
  accountReducer,
  AppEffects,
  AppFacade,
  appReducer,
  AuthnEffects,
  AuthnFacade,
  authnReducer,
  CountryEffects,
  CountryFacade,
  CurrencyEffects,
  CurrencyFacade,
  countryReducer,
  FulfillmentEffects,
  FulfillmentFacade,
  fulfillmentReducer,
  IamEffects,
  IamFacade,
  iamReducer,
  InvoiceEffects,
  InvoiceFacade,
  invoiceReducer,
  LocaleEffects,
  LocaleFacade,
  localeReducer,
  OrganizationEffects,
  OrganizationFacade,
  organizationReducer,
  OrganizationContextEffects,
  OrganizationContextFacade,
  organizationContextReducer,
  ProductEffects,
  ProductFacade,
  productReducer,
  RoleEffects,
  RoleFacade,
  roleReducer,
  RouterFacade,
  TimezoneEffects,
  TimezoneFacade,
  timezoneReducer,
  currencyReducer,
  TaxFacade,
  taxReducer,
  TaxEffects,
  ShopFacade,
  shopReducer,
  ShopEffects,
  policyReducer,
  PolicyEffects,
  PolicyFacade,
  ObjectUploadFacade,
  objectUploadReducer,
  ObjectUploadEffects,
  ManufacturerEffects,
  manufacturerReducer,
  ManufacturerFacade,
  productCategoryReducer,
  PriceGroupEffects,
  priceGroupReducer,
  ProductCategoryEffects,
  PriceGroupFacade,
  ProductCategoryFacade,
  ProductPrototypeEffects,
  ProductPrototypeFacade,
  productPrototypeReducer,
  CustomerFacade,
  customerReducer,
  CustomerEffects,
} from './+state';

const facades = [
  AccountFacade,
  AppFacade,
  AuthnFacade,
  CountryFacade,
  CurrencyFacade,
  CustomerFacade,
  FulfillmentFacade,
  InvoiceFacade,
  IamFacade,
  OrganizationFacade,
  RoleFacade,
  LocaleFacade,
  ManufacturerFacade,
  OrganizationContextFacade,
  ProductFacade,
  RouterFacade,
  TaxFacade,
  TimezoneFacade,
  ShopFacade,
  PolicyFacade,
  PriceGroupFacade,
  ObjectUploadFacade,
  ProductCategoryFacade,
  ProductPrototypeFacade,
];

@NgModule({
  imports: [
    StoreModule.forFeature(STORE.states.appState, appReducer),
    EffectsModule.forFeature([AppEffects]),
    StoreModule.forFeature(STORE.states.accountState, accountReducer),
    EffectsModule.forFeature([AccountEffects]),
    StoreModule.forFeature(STORE.states.authnState, authnReducer),
    EffectsModule.forFeature([AuthnEffects]),

    EffectsModule.forFeature([IamEffects]),
    StoreModule.forFeature(STORE.states.organizationState, organizationReducer),
    EffectsModule.forFeature([OrganizationEffects]),
    StoreModule.forFeature(STORE.states.roleState, roleReducer),
    EffectsModule.forFeature([RoleEffects]),
    StoreModule.forFeature(STORE.states.localeState, localeReducer),
    EffectsModule.forFeature([LocaleEffects]),
    StoreModule.forFeature(STORE.states.policyState, policyReducer),
    EffectsModule.forFeature([PolicyEffects]),
    StoreModule.forFeature(STORE.states.productState, productReducer),
    EffectsModule.forFeature([ProductEffects]),
    StoreModule.forFeature(
      STORE.states.organizationContextState,
      organizationContextReducer
    ),
  ],
  providers: [...facades],
})
export class CoreStateModule {}
