import { NgModule } from '@angular/core';
import { EffectsModule } from '@ngrx/effects';
import * as fromRouter from '@ngrx/router-store';
import { StoreModule } from '@ngrx/store';

import { STORE } from '@console-core/config';

import {
  AccountEffects,
  AccountFacade,
  accountReducer,
  AppEffects,
  AppFacade,
  appReducer,
  AuthnEffects,
  AuthnFacade,
  authnReducer,
  CountryEffects,
  CountryFacade,
  CurrencyEffects,
  CurrencyFacade,
  countryReducer,
  FulfillmentEffects,
  FulfillmentFacade,
  fulfillmentReducer,
  IamEffects,
  IamFacade,
  iamReducer,
  InvoiceEffects,
  InvoiceFacade,
  invoiceReducer,
  LocaleEffects,
  LocaleFacade,
  localeReducer,
  OrderEffects,
  OrderFacade,
  orderReducer,
  OrganizationEffects,
  OrganizationFacade,
  organizationReducer,
  OrganizationContextEffects,
  OrganizationContextFacade,
  organizationContextReducer,
  ProductEffects,
  ProductFacade,
  productReducer,
  RoleEffects,
  RoleFacade,
  roleReducer,
  RouterFacade,
  TimezoneEffects,
  TimezoneFacade,
  timezoneReducer,
  currencyReducer,
  TaxFacade,
  taxReducer,
  TaxEffects,
  ShopFacade,
  shopReducer,
  ShopEffects,
  policyReducer,
  PolicyEffects,
  PolicyFacade,
  ObjectUploadFacade,
  objectUploadReducer,
  ObjectUploadEffects,
  ManufacturerEffects,
  manufacturerReducer,
  ManufacturerFacade,
  productCategoryReducer,
  PriceGroupEffects,
  priceGroupReducer,
  ProductCategoryEffects,
  PriceGroupFacade,
  ProductCategoryFacade,
  ProductPrototypeEffects,
  ProductPrototypeFacade,
  productPrototypeReducer,
  CustomerFacade,
  customerReducer,
  CustomerEffects,
} from './+state';

const facades = [
  AccountFacade,
  AppFacade,
  AuthnFacade,
  CountryFacade,
  CurrencyFacade,
  CustomerFacade,
  FulfillmentFacade,
  InvoiceFacade,
  IamFacade,
  OrganizationFacade,
  RoleFacade,
  LocaleFacade,
  ManufacturerFacade,
  OrderFacade,
  OrganizationContextFacade,
  ProductFacade,
  RouterFacade,
  TaxFacade,
  TimezoneFacade,
  ShopFacade,
  PolicyFacade,
  PriceGroupFacade,
  ObjectUploadFacade,
  ProductCategoryFacade,
  ProductPrototypeFacade,
];

@NgModule({
  imports: [
    StoreModule.forFeature(STORE.states.appState, appReducer),
    EffectsModule.forFeature([AppEffects]),
    StoreModule.forFeature(STORE.states.accountState, accountReducer),
    EffectsModule.forFeature([AccountEffects]),
    StoreModule.forFeature(STORE.states.authnState, authnReducer),
    EffectsModule.forFeature([AuthnEffects]),
    StoreModule.forFeature(STORE.states.countryState, countryReducer),
    EffectsModule.forFeature([CountryEffects]),
    StoreModule.forFeature(STORE.states.currencyState, currencyReducer),
    EffectsModule.forFeature([CurrencyEffects]),
    StoreModule.forFeature(STORE.states.fulfillmentState, fulfillmentReducer),
    EffectsModule.forFeature([FulfillmentEffects]),
    StoreModule.forFeature(STORE.states.invoiceState, invoiceReducer),
    EffectsModule.forFeature([InvoiceEffects]),
    StoreModule.forFeature(STORE.states.iamState, iamReducer),
    EffectsModule.forFeature([IamEffects]),
    StoreModule.forFeature(STORE.states.organizationState, organizationReducer),
    EffectsModule.forFeature([OrganizationEffects]),
    StoreModule.forFeature(STORE.states.roleState, roleReducer),
    EffectsModule.forFeature([RoleEffects]),
    StoreModule.forFeature(STORE.states.localeState, localeReducer),
    EffectsModule.forFeature([LocaleEffects]),
    StoreModule.forFeature(STORE.states.orderState, orderReducer),
    EffectsModule.forFeature([OrderEffects]),
    StoreModule.forFeature(STORE.states.policyState, policyReducer),
    EffectsModule.forFeature([PolicyEffects]),
    StoreModule.forFeature(STORE.states.productState, productReducer),
    EffectsModule.forFeature([ProductEffects]),
    StoreModule.forFeature(STORE.states.timezoneState, timezoneReducer),
    StoreModule.forFeature(STORE.states.taxState, taxReducer),
    EffectsModule.forFeature([TaxEffects]),
    EffectsModule.forFeature([TimezoneEffects]),
    StoreModule.forFeature(STORE.states.shopState, shopReducer),
    EffectsModule.forFeature([ShopEffects]),
    StoreModule.forFeature(STORE.states.manaufacturer, manufacturerReducer),
    EffectsModule.forFeature([ManufacturerEffects]),
    StoreModule.forFeature(STORE.states.routerState, fromRouter.routerReducer),
    // EffectsModule.forFeature([OrganizationContextEffects]),
    StoreModule.forFeature(STORE.states.objectUploadState, objectUploadReducer),
    EffectsModule.forFeature([ObjectUploadEffects]),
    StoreModule.forFeature(STORE.states.priceGroup, priceGroupReducer),
    EffectsModule.forFeature([PriceGroupEffects]),
    StoreModule.forFeature(STORE.states.customerState, customerReducer),
    EffectsModule.forFeature([CustomerEffects]),
    StoreModule.forFeature(
      STORE.states.productCategory,
      productCategoryReducer
    ),
    EffectsModule.forFeature([ProductCategoryEffects]),
    StoreModule.forFeature(
      STORE.states.productPrototype,
      productPrototypeReducer
    ),
    EffectsModule.forFeature([ProductPrototypeEffects]),
    StoreModule.forFeature(
      STORE.states.organizationContextState,
      organizationContextReducer
    ),
  ],
  providers: [...facades],
})
export class CoreStateModule {}
