name: build

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '20.12.1'

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Build
        run: npm run console:build:prod

  image:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Set variables
        id: vars
        run: |
          echo ::set-output name=version_tag::$(echo ${GITHUB_REF#refs/*/})
          echo ::set-output name=repo_name::$(echo ${GITHUB_REPOSITORY#*/*})

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          build-args: |
            APP_HOME=/home/node/${{ steps.vars.outputs.repo_name }}
          cache-from: |
            ${{ github.repository }}:latest
